name: "Secure Scan Action"
description: "Scans your repository for security vulnerabilities using Trivy and analyzes vulnerable package(s) usage with AST-Grep"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'shield'
  color: 'green'
