name: Self Scan

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Action repository
        uses: actions/checkout@v4

      - name: Run secure-scan-action on itself
        uses: ./
        with:
          scanners: trivy
          severity: HIGH